### ISSUE TITLE
Cmake error when compiling ros_tutorials packages in windows 10 ROS 2 Foxy Fitzroy Patch Release 4

### ISSUE THREAD

**Issue by andrestoga** [ros2/ros2#1083]
## Bug report

**Required Info:**

- Operating System:
  Windows 10
- Installation type:
  binaries
- Version or commit hash:
ROS 2 Foxy Fitzroy Patch Release 4
- DDS implementation:
Fast-RTPS
- Client library (if applicable):
rclcpp

#### Steps to reproduce issue

I just followed the instructions in [Installing ROS 2 on Windows](https://index.ros.org/doc/ros2/Installation/Foxy/Windows-Install-Binary/). After that, I tried to create a workspace following [this tutorial](https://index.ros.org/doc/ros2/Tutorials/Workspace/Creating-A-Workspace/) but at step 5, I'm getting the following error:

> C:\dev_ws>colcon build --merge-install
> Starting >>> turtlesim
> --- stderr: turtlesim
> CMake Error at CMakeLists.txt:15 (find_package):
>   By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Qt5", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5" with any of
>   the following names:
> 
>     Qt5Config.cmake
>     qt5-config.cmake
> 
>   Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
>   to a directory containing one of the above files.  If "Qt5" provides a
>   separate development package or SDK, be sure it has been installed.
> 
> Failed   <<< turtlesim [1.20s, exited with code 1]
> 
> Summary: 0 packages finished [1.39s]
>   1 package failed: turtlesim
>   1 package had stderr output: turtlesim

#### Expected behavior

> Starting >>> turtlesim
> Finished <<< turtlesim [5.49s]
> 
> Summary: 1 package finished [5.58s]

#### Actual behavior

Got an error described above

#### Additional information

This question has been asked on https://answers.ros.org but no answers yet. Here's the [link](https://answers.ros.org/question/368502/cmake-error-when-creating-a-new-workspace-in-windows/). It's weird because on the installing tutorial(binaries) doesn't say anything about extending the variable "CMAKE_PREFIX_PATH" to include the Qt5 directory. Not even in the "Building ROS 2 on Windows" tutorial. I found some Qt folders in the share folder of the zip installation. I'm guessing I don't need to install Qt because the installation already comes with it. Moreover, "CMAKE_PREFIX_PATH" already points to the installation directory: "C:\dev\ros2_foxy" where those Qt folders are.

**Comment by tfoote** [comment]
Answer.ros.org is the correct place to ask a question like this. Please don't repost questions on our issue tracker, this is not the right place following our [Support Policy](https://wiki.ros.org/Support)

That question does not have enough information to reproduce the problem which is likely why it doesn't have any answers.  You've provide more information such that someone could reproduce. However this is now in the wrong place. Please ask for help on answers.ros.org and then add a comment to the existing question with a link to your question saying that you think it's a duplicate so that if others find it they can get to your more complete question which will be much more likely to get an answer.
