### ISSUE TITLE
Missing devel folder

### ISSUE THREAD

**Issue by NattanonCM** [ros2/ros2#1607]
Rn I use ros2 and I already create workspace. I also do colcon build but the devel folder not created.
(I try to use lidar)
(Also I am new)

(In my ros ws)
$source devel/setup.bash
-bash: devel/setup.bash: No sush file or directory
$ls
build install log src

**Comment by clalancette** [comment]
That is by design; in ROS 2, we only have an `install` folder, no `devel` folder.  See https://design.ros2.org/articles/build_tool.html , as well as https://colcon.readthedocs.io/en/released/user/quick-start.html?highlight=devel%20space (which gives some idea of the differences with ROS 1).

In the future, please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.
