### ISSUE TITLE
ACCESS-OUTOF_BOUND issue 2

### ISSUE THREAD

**Issue by SoftSec-Tech** [ros2/ros2#1620]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - from source 
- Version or commit hash:
  - LATEST
- DDS implementation:
  - no
- Client library (if applicable):
  - no

#### Steps to reproduce issue
Code analyzed by static analysis tool - StatiCode from Software Security Technology Co, Ltd. This is an ACCESS-OUTOF_BOUND issue.
![屏幕截图 2024-11-04 174524](https://github.com/user-attachments/assets/9da32887-95aa-4529-9b96-1debe6975cba)

#### Additional information

----

**Comment by fujitatomoya** [comment]
@SoftSec-Tech thanks for creating issue.

Actually the source code where static analyzer complains is NOT maintained by ROS 2 project.
If we are building from the source code (https://docs.ros.org/en/rolling/Installation/Alternatives/Ubuntu-Development-Setup.html#build-ros-2), https://github.com/ros2/rosbag2/tree/rolling/zstd_vendor fetches the specific version of `zstd` to the build environment and get built.

We would like to suggest the followings.

- analyzer report can be reported to https://github.com/facebook/zstd, that is where the source code is maintained. (I am not sure if this analyzer claim is fixed in the latest version of zstd.)
- if the zstd version that ROS 2 uses (e.g `rolling` https://github.com/ros2/rosbag2/blob/b5098eff15281c9e79853e8bb2ae9a0a104e6ea5/zstd_vendor/CMakeLists.txt#L16) still has the reported problems, we may need to consider to upgrade the zstd version ROS 2 uses. in that case, we suggest that you can create the issue on https://github.com/ros2/rosbag2/tree/rolling/zstd_vendor, that is where it controls the zstd version for ROS 2.

with above description, i will go ahead to close this issue for now. please feel free and consider to (re)open the issue to https://github.com/ros2/rosbag2 instead.
