### ISSUE TITLE
Alpha 6 (2016-05-18)

### ISSUE THREAD

**Issue by gerkey** [ros2/ros2#212]
* [x] Support nested messages in Python (1 week) ros2/rosidl#113 ros2/rosidl#119 @mikaelarguedas
  * [ ] connext_dynamic support
* [x] Refactor rclcpp to use rcl (1 week) ros2/rclcpp#204 @jacquelinekay 
* [x] ROS 2 wrapper for joystick input @codebot

**Comment by jacquelinekay** [comment]
Thinking of also making a general (not necessarily Turtlebot-specific) `launch` tutorial and a parameters tutorial as a goal of this alpha.

**Comment by dirk-thomas** [comment]
We talked about the logging subsystem in todays meeting and decided to include a namespace hierarchy in the core logging API. Therefore the current `console_bridge` API won't work as-is since it doesn't support namespacing. It either needs to be revised with a new API or a similar replacement is required.

**Comment by dirk-thomas** [comment]
Released today.
