### ISSUE TITLE
can't use ament in linux using pre-built libraries

### ISSUE THREAD

**Issue by bbaillio** [ros2/ros2#220]
I downloaded the alpha5 release package here: https://github.com/ros2/ros2/releases.
I extract, and then source the setup.bash file.
If I run ament, I get the following error:
`bash: /home/platform/Asi/ros2-linux/bin/ament: /home/rosbuild/ci_scripts/ws/venv/bin/python: bad interpreter: No such file or directory`

I get the same response if I try to run the listener_py or talker_py programs.

I am able to run the non-python example programs, like `talker` and `listener`.

**Comment by wjwwood** [comment]
This is a known issue: https://github.com/ros2/ros2/issues/141

We "worked around" it for the `setup.*sh` files, but it remains an issue with any Python script. That's why the tutorials (https://github.com/ros2/ros2/wiki/Python-Programming#run-the-examples) do this:

```
$ python3 `which talker_py`
$ python3 `which listener_py`
```

Similarly you could invoke ament this way:

```
$ python3 `which ament`
```

I'll close this as a duplicate.
