### ISSUE TITLE
Unify Jenkins batch jobs

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#36]
Acceptance Criteria:

- [x] Jenkins jobs are parameterized on:
 - [x] branch to use on ros2/ros2, defaults to `ci_scripts`.
 - [x] whitespace in paths, e.g. workspace, source, build and install spaces.
 - [x] whether or not to try to use Connext.
- [x] Unify Jenkins jobs a much as possible.
- [x] Minimize the platform specific differences in the jobs.

**Comment by dirk-thomas** [comment]
We should consider to generate multiple jobs per platform. E.g. on Linux we should have one job using the official Connext binary package and another one using our custom Debian package.

**Comment by wjwwood** [comment]
Ok, I've parameterized a version of the Windows job, please take a look and if there are no suggestions, I'll move forward making the OS X and Linux jobs very similar.

**Comment by wjwwood** [comment]
http://54.183.26.131:8080/job/ros2_batch_ci_windows_experimental/

**Comment by dirk-thomas** [comment]
The first build with a custom branch looked good (number 16, I aborted it after seeing the correct checkout).

I then tried with spaces (http://54.183.26.131:8080/job/ros2_batch_ci_windows_experimental/17/) and that seems to fail. The PYTHONPATH seems to be wrong - likely a problem in one of the bat files.

**Comment by dirk-thomas** [comment]
When switching between spaces and no spaces it also does not clean the other workspace folder from previous builds.

**Comment by wjwwood** [comment]
> I then tried with spaces (http://54.183.26.131:8080/job/ros2_batch_ci_windows_experimental/17/) and that seems to fail. The PYTHONPATH seems to be wrong - likely a problem in one of the .bat files?

In this issue I'm really only concerned about whether or not the correct folders were passed to the tools, not whether or not our entire software stack support whitespace since we have outstanding known issues.

> When switching between spaces and no spaces it also does not clean the other workspace folder from previous builds.

It does, it just doesn't clear previous builds of a different configuration. If you build spaces, no spaces, then spaces again it will remove the first one with spaces. I'd rather not force the tool to remove all possible workspace folders on each run, because when using it locally I would like to switch back and forth between spaces and no spaces without clearing each other. So I've added a `rmdir /S /Q workspace "work space"` to the Jenkins job configuration.

**Comment by dirk-thomas** [comment]
Since the failing job when white spaces are enabled is specific to the Windows build I would say it looks good and you can go ahead and use the same template for Linux / OS X.

**Comment by wjwwood** [comment]
Ok, I think this is ready for review. I have a "launcher" job which will spawn each of the other three batch jobs, forwarding along the options:

- http://54.183.26.131:8080/job/ros2_batch_ci_launcher/

Then we have each of the jobs:

- http://54.183.26.131:8080/job/ros2_batch_ci_linux/
- http://54.183.26.131:8080/job/ros2_batch_ci_osx/
- http://54.183.26.131:8080/job/ros2_batch_ci_windows/

The jobs are all created by a Python script:

- https://github.com/ros2/ros2/blob/ci_scripts/create_jenkins_job.py

Instructions on how to deploy on a new farm are in the `README.md`:

- https://github.com/ros2/ros2/blob/ci_scripts/README.md

There are still several issues, but I think we can address those separately rather than drag this issue on:

- Linux doesn't find RTI with the current `.deb`'s, but @esteve is working on that.
- OS X doesn't build with Connext set to ON, so the launcher job could be made to let the user select 'on', 'off', or additionally 'default' for the connext option so that you can at least test Linux and Windows with Connext on without worrying about OS X breaking. Hopefully in the future such flexibility won't be needed.
- Windows, Linux, and OS X don't have the right version of uncrustify, but @dirk-thomas is working on that.

@dirk-thomas @esteve @tfoote for review.

**Comment by wjwwood** [comment]
I've also merged `ci_scripts2` into `ci_scripts` and removed the extra jobs.

**Comment by dirk-thomas** [comment]
The license file on the branch (https://github.com/ros2/ros2/blob/ci_scripts/LICENSE) is not identical to the template (white spaces before the first content line). Also the license file should not contain the year and osrf reference. Instead that should only be part of the source files.

**Comment by dirk-thomas** [comment]
The script `create_jenkins_job.py` contains a lot of xml for the job configuration. Should this be extracted into "snippet" files for easier reading / editing? Similar as for the ros_buildfarm repo.

**Comment by wjwwood** [comment]
LICENSE file has been updated and I moved the job xml templates out of the python script.

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
+1

**Comment by esteve** [comment]
+1

**Comment by esteve** [comment]
The Linux slave now finds Connext properly: http://54.183.26.131:8080/view/ros2/job/ros2_batch_ci_linux/15/console

**Comment by wjwwood** [comment]
@esteve can you make a pull request to merge your version of `ci_scripts`?

**Comment by esteve** [comment]
@wjwwood https://github.com/ros2/ros2/pull/39
