### ISSUE TITLE
[wiki edit] duplicate addition of catkin_pkg to the Linux source install page

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros2#505]
@Martin-Idel-SI your last [wiki edit](https://github.com/ros2/ros2/wiki/Linux-Development-Setup/_compare/e3a10ed200d5502948b571a70bdef2776fb542bd...c710834d84d47d00b0c0e350f0f9b173695182b6) looks like a duplicate of [this one from yesterday](https://github.com/ros2/ros2/wiki/Linux-Development-Setup/_compare/7e83907217fa0bbba4d8a071ce48eaead67827e0...36a275e605ac99891524bbdb2ce946a0587b7186) with the downside that it installs from pip.

Can you confirm if installing from apt and not pip allows you to build workspaces successfully?

**Comment by dirk-thomas** [comment]
I just [reverted](https://github.com/ros2/ros2/wiki/Linux-Development-Setup/_compare/c710834d84d47d00b0c0e350f0f9b173695182b6...a64631205df49ddc9424382ed3760de4757bec54) the change since it is not desired to install the package via `pip`.

If that is not sufficient for any reason please comment and this can be reopened.
