### ISSUE TITLE
Do You Really Test New Version On Windows10 ?

### ISSUE THREAD

**Issue by yuanzhiyu** [ros2/ros2#556]
a lot of troubles, even in local_setup.sh the system remind me it exists grammar errors

**Comment by dirk-thomas** [comment]
Yes, we do. All tests are being run on Linux, macOS and Windows.

Since you ask about Windows I am not sure how `local_setup.sh` and 'grammar errors" are related. On Windows only the `.bat` files are being used.

Since your question doesn't contain any more context I assume my comment answers it. Therefore I will go ahead and close this ticket. If you want to describe a more specific question please feel free to comment and the issue can be reopened if necessary.
