### ISSUE TITLE
build without atomic support

### ISSUE THREAD

**Issue by vingtfranc** [ros2/ros2#628]
Hi,

I would like to build ROS 2 on an embedded system that does not support atomic operation. I know that rcl and rclcpp both use a few atomics, but is there any way to work around this and compile ROS 2 without any atomic?

**Comment by wjwwood** [comment]
I'm going to close this for now, since if we want to turn this into a feature request then I think it needs to be reopened on `rcl` and/or `rclcpp`.

If you want to do more general discussion about getting it working for a specific embedded case, I think https://discourse.ros.org/ is more appropriate, moving only to GitHub issues when actionable items are found.

I'm going to close this for now, but feel free to continue commenting here, and if needed I can reopen this issue.
