### ISSUE TITLE
Crystal release For OSX missing ament

### ISSUE THREAD

**Issue by davidhodo** [ros2/ros2#629]
The 20181214 Crystal release For OSX found at: [https://github.com/ros2/ros2/releases/download/release-crystal-20181214/ros2-crystal-20181214-osx-x86_64.tar.bz2](https://github.com/ros2/ros2/releases/download/release-crystal-20181214/ros2-crystal-20181214-osx-x86_64.tar.bz2) is missing the ament executable in the bin folder.

**Comment by wjwwood** [comment]
I believe that is intentional, colcon replaced ament_tools in the previous release (bouncy) and was removed in this release.

See the top of this tutorial: https://index.ros.org/doc/ros2/Ament-Tutorial/

Also: https://github.com/ros2/ros2/issues/584

I'm going to close this because I believe the issue has been addressed. Feel free to continue to comment and I can reopen if necessary.
