### ISSUE TITLE
ROS 2 Drivers for OXTS GPS/IMU products

### ISSUE THREAD

**Issue by NEUUGV** [ros2/ros2#766]
Hello ROS developers! 
I would like make use of an OXTS GPS/IMU product (i.e., a RT2000 system component) under ROS 2 Dashing Diademata. Therefore, I wonder if there exist ROS 2 Dashing Diademata drivers for OXTS GPS/IMU products.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
