### ISSUE TITLE
ROS 2 Performance Test Infrastructure

### ISSUE THREAD

**Issue by cottsay** [ros2/ros2#812]
Leverage existing performance testing tools to create infrastructure to compare the performance between DDS implementations, track performance trends over time, aid in root-causing performance regressions, and prevent them from happening in the first place.

At the moment, the only suite targeted to run is the [`performance_test`](https://github.com/ApexAI/performance_test) package written by Apex.AI. To that end, there is some outstanding work:
* Support ROS 2 Eloquent (ApexAI/performance_test#89)
* Support multiple participants for CycloneDDS (ApexAI/performance_test#90)

- [x] Create job in `ros_buildfarm` to run the test suite
       The job must:
    - [x] Build the performance test code
    - [x] Build the performance test code for Eloquent ([GitLab ApexAI/performance_test#111](https://gitlab.com/ApexAI/performance_test/merge_requests/111))
    - [x] Run the jobs for some number of DDS implementations ([staging repo](https://github.com/cottsay/buildfarm_perf_tests) - not a final design)
    - [x] Aggregate the results and display them in Jenkins
        - [x] Facilitate analysis per-build (ros-infrastructure/ros_buildfarm#680)
        - [x] Facilitate analysis over time

Some other desirable work might be to hook into an external data analysis tool. The tool should ideally be available freely like the rest of the ROS 2 infrastructure is.

**Comment by ahcorde** [comment]
I have created this two PRs to include the work taht @cottysay has done:

 - https://github.com/ros2/ros_buildfarm_config/pull/51
 - https://github.com/ros-infrastructure/ros_buildfarm/pull/689

**Comment by dirk-thomas** [comment]
Items from past offline conversations:
* [ ] document what exactly is being tested
* [ ] document how to reproduce it locally

Before sharing the results / pointer to the docs on Discourse we should gather feedback from all vendors (to provide "neutral" statistics).

**Comment by ahcorde** [comment]
@dirk-thomas  Documentation of how to reproduce it locally is in the [Readme.md](https://github.com/ros2/buildfarm_perf_tests)

**Comment by ahcorde** [comment]
We are testing two different things. One one hand we are measuremtn the performance of the DDS vendors and on the other hand we are evaluating the additional overhead caused by a single pub-sub topic or one process spinning and detec potential leaks related to theses activities.

## Test 1 - Performance Test  (APEX.AI)

In this test we are testing the  Performance Test provided by APEX.AI. Right now we have [our own fork](https://github.com/ros2/performance_test) because there are two pending pull request in the official gitlab repository.

In this test we are measurement:
 - Average round-trip time
 - CPU usage (provided by APEX.AI tool)
 - Sent/Received packets per second
 - Total lost packets
 - Max resident set size

We are generating two plots per measurement
 - [One per per-build](http://build.ros2.org/view/Eci/job/Eci__nightly-performance_ubuntu_bionic_amd64/lastBuild/)
 - [Other over time](http://build.ros2.org/view/Eci/job/Eci__nightly-performance_ubuntu_bionic_amd64/plot/)

| Publisher/Subscriber     | rmw_fastrtps_cpp         | rmw_opensplice_cpp       | rmw_cyclonedds_cpp       | rmw_fastrtps_dynamic_cpp | rmw_connext_cpp          |
|--------------------------|--------------------------|--------------------------|--------------------------|--------------------------|--------------------------|
| rmw_fastrtps_cpp         | :heavy_check_mark:       | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: |
| rmw_opensplice_cpp       | :heavy_multiplication_x: | :heavy_check_mark:       | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: |
| rmw_cyclonedds_cpp       | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_check_mark:       | :heavy_multiplication_x: | :heavy_multiplication_x: |
| rmw_fastrtps_dynamic_cpp | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_check_mark:       | :heavy_multiplication_x: |
| rmw_connext_cpp          | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_check_mark:       |

## Test 2 - Simple pub/sub 

In this case we are testing one publisher and one subscriber **in different processes** sending a 1kArray at 5Hz. This will allow us to 
 evaluate additional overhead caused by a single pub-sub topic and detect leaks related to this
activity.

We measurement for both publisher and subscriber:

 - Average round trip 
 - CPU usage ( readed from the filesystem )
 - Total lost packets
 - Received/Sent packets
 - Physical memory (Mb)
 - Resident anonymous memory (Mb)
 - Virtual memory (Mb)

Again we plot measurement:
 - [One per per-build](http://3.83.10.11/job/Dci__nightly-performance-overhead-multi_ubuntu_bionic_amd64/lastBuild/)
 - [Other over time](http://3.83.10.11/job/Dci__nightly-performance-overhead-multi_ubuntu_bionic_amd64/plot/)

| Publisher/Subscriber     | rmw_fastrtps_cpp   | rmw_opensplice_cpp | rmw_cyclonedds_cpp | rmw_fastrtps_dynamic_cpp | rmw_connext_cpp    |
|--------------------------|--------------------|--------------------|--------------------|--------------------------|--------------------|
| rmw_fastrtps_cpp         | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:       | :heavy_check_mark: |
| rmw_opensplice_cpp       | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:       | :heavy_check_mark: |
| rmw_cyclonedds_cpp       | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:       | :heavy_check_mark: |
| rmw_fastrtps_dynamic_cpp | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:       | :heavy_check_mark: |
| rmw_connext_cpp          | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:       | :heavy_check_mark: |

## Test 3 - Node spinning

This test creates one process and spin for 1 minute to evaluate ROS 2 overhead and detect obvious leaks.

We measurement:

 - CPU usage ( readed from file system )
 - Physical memory
 - Resident anonymous memory
 - Virtual memory

Again we plot measurement:
 - [One per per-build](http://3.83.10.11/job/Dci__nightly-performance-overhead_ubuntu_bionic_amd64/lastBuild/)
 - [Other over time](http://3.83.10.11/job/Dci__nightly-performance-overhead_ubuntu_bionic_amd64/plot/Node%20Spinnig%20Results/)

| DDS                      | Process 1 |
|--------------------------|-----------|
| rmw_fastrtps_cpp         | :heavy_check_mark:   |
| rmw_opensplice_cpp       |  :heavy_check_mark:   |
| rmw_cyclonedds_cpp       | :heavy_check_mark:   |
| rmw_fastrtps_dynamic_cpp |  :heavy_check_mark:   |
| rmw_connext_cpp          |   :heavy_check_mark:   |

**Comment by ahcorde** [comment]
# Notes

Test 2 and Test 3 are not upstream yet.

Where I should locate this documentation?

**Comment by ahcorde** [comment]
https://github.com/ros2/buildfarm_perf_tests/pull/11

**Comment by chapulina** [comment]
👍
