### ISSUE TITLE
ROS Mapping error

### ISSUE THREAD

**Issue by benjamin1203** [ros2/ros2#846]
Hi all , I had just picked up ROS recently for a project that I am currently working on regarding autonomous robots. So I was trying to get the mapping process going , I have with me a UPsquared connected to a RPlidar A1 and I am accessing the UPsquared through my computer. I launched the rplidar launch file first , then the gmapping launch file from another terminal. On the gmapping.launch terminal I got this error message :
[ WARN] [1577691725.782039473]: MessageFilter [target=odom ]: Dropped 100.00% of messages so far. Please turn the [ros.gmapping.message_notifier] rosconsole logger to DEBUG for more information.
I do not know how to solve this error and am stuck , please help.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
