### ISSUE TITLE
can't find tinyxml2::tinyxml2

### ISSUE THREAD

**Issue by Karsten1987** [ros2/ros2#927]
## Bug report

**Required Info:**

Packages (indirectly) depending on `tinyxml2` might fail, because the taget `tinyxm2::tinyxml2` is not found. 
```
02:59:47 CMake Error at CMakeLists.txt:35 (add_library):
02:59:47   Target "rosbag2_transport" links to target "tinyxml2::tinyxml2" but the
02:59:47   target was not found.  Perhaps a find_package() call is missing for an
02:59:47   IMPORTED target, or an ALIAS target is missing?
```

This happened at `rviz_common` as well as `rosbag2_transport` and is heavily depend on the include order of packages - the order in which `find_package` is called.

See the example of rviz common here: https://github.com/ros2/rviz/pull/542/commits/b327b438aefec3b5ccd6142e1ab255de19d14be4

- Operating System:
  - Windows 10
- Installation type:
  - Source, partially provoked by building with `-DENABLE_TESTING=OFF`

#### Steps to reproduce issue

Revert the commit in here: https://github.com/ros2/rviz/pull/542/commits/b327b438aefec3b5ccd6142e1ab255de19d14be4 

or look at the current Windows packaging job: https://ci.ros2.org/view/packaging/job/packaging_windows/1752/console#console-section-20

Note that for the latter, the packaging job fails because `ENABLE_TESTING=OFF`, whereas the build succeeds if tests are built.

#### Expected behavior

The order in which `find_package` doesn't matter, meaning packages can be sorted alphabetically.

#### Actual behavior

The order _does_ matter! In the example of `tinyxml2`, whenever being `find_package`'d first, the compilation goes through smoothly. Being find first, also implies being found via `find_package(pluginlib)` or any other package exporting the dependency of `tinyxml2`.

**Comment by dirk-thomas** [comment]
The reason why the order matters is as follows:

* `pluginlib` first finds `tinyxml2_vendor` (which extends the search path for CMake modules) and then finds `TinyXML2`
* Other packages recursively depending on FastRTPS trigger the CMake config logic of FastRTPS which just finds `TinyXML2` (without using the vendor package)

If the second happens before the first the result is that `TinyXML2` has already been found without using the vendor logic and not using it to search for `TinyXML2` again since the previously cached result is being reused.
