### ISSUE TITLE
ros2 topic list, ros2 msg list not working

### ISSUE THREAD

**Issue by Mihirkaswan** [ros2/ros2#998]
## Bug report

**Required Info:**

- Operating System:
  - Mac Os Catalina version 10.15.3
- Installation type:
  - Source
- Version or commit hash:
  - ROS 2 Foxy Fitzroy`fc010c9`
- DDS implementation:
  - Not done
- Client library (if applicable):
  -  N/A 

#### Steps to reproduce issue
`>> ros2 topic list` not working
```
Failed to load entry point 'list': No module named 'netifaces'
Traceback (most recent call last):
  File "/Users/mihirkaswan/ros2_crystal/ros2-osx/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.9.5', 'console_scripts', 'ros2')()
  File "/Users/mihirkaswan/ros2_crystal/ros2-osx/lib/python3.8/site-packages/ros2cli/cli.py", line 39, in main
    add_subparsers_on_demand(
  File "/Users/mihirkaswan/ros2_crystal/ros2-osx/lib/python3.8/site-packages/ros2cli/command/__init__.py", line 249, in add_subparsers_on_demand
    extension.add_arguments(
  File "/Users/mihirkaswan/ros2_crystal/ros2-osx/lib/python3.8/site-packages/ros2topic/command/topic.py", line 29, in add_arguments
    add_subparsers_on_demand(
  File "/Users/mihirkaswan/ros2_crystal/ros2-osx/lib/python3.8/site-packages/ros2cli/command/__init__.py", line 236, in add_subparsers_on_demand
    extension = command_extensions[name]
KeyError: 'list'
```
 `>>ros2 msg list` not working

```
usage: ros2 [-h] Call `ros2 <command> -h` for more detailed usage. ...
ros2: error: argument Call `ros2 <command> -h` for more detailed usage.: invalid choice: 'msg' (choose from 'action', 'bag', 'component', 'daemon', 'doctor', 'extension_points', 'extensions', 'interface', 'launch', 'lifecycle', 'multicast', 'node', 'param', 'pkg', 'run', 'security', 'service', 'test', 'topic', 'trace', 'wtf')
```

#### Additional information
My talker and receiver are working properly. When is tried to install 'netifaces' it is saying that already installed.
```
>> pip3 install netifaces
Requirement already satisfied: netifaces in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (0.10.9)
```

**Comment by clalancette** [comment]
We don't officially support macOS Catalina on any released ROS 2 distribution.  So in that sense, you are in new (and unsupported) territory.

There are a few different things going on here.

1. In Foxy, we have completely removed the `ros2 msg` command, and it has been replaced by `ros2 interface`.  So that is expected not to work anymore.
1.  The pathnames in your output above all have the word "crystal" in it.  I don't think you are actually using Crystal, but it is a bit confusing.
1.  The fact that it can't import `netifaces` is what is causing list not to work.  I'm guessing that this probably has to do with what version of python3 you are using.  Given the path location that is failing, I'm guessing you actually have python3 installed twice; once from brew and once another way.  You probably have netifaces installed in the second way, but not in the brew installed version.  Since `ros2` is probably using the brew version, you are still missing it.  I'd suggest uninstalling python3 from `/Library/Frameworks/Python.framework`, and reinstalling it via brew.

In the future, please open questions like this on https://answers.ros.org.  That way we can have all of the questions and answers in one searchable place.  I'm going to close this out.
